version: '2'
services:
  nginx:
    image: nginx:1.12.2-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./log/nginx/:/var/log/nginx
      - ./apps:/apps
      - ./images/nginx/network_internal.conf:/etc/nginx/network_internal.conf:ro
      - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images/nginx/conf.d:/etc/nginx/conf.d
      - ./images/nginx/certs:/etc/nginx/certs
      - ./images/nginx/dhparam:/etc/nginx/dhparam
      - ./images/nginx/htpasswd:/etc/nginx/htpasswd
      - ./images/nginx/vhost.d:/etc/nginx/vhost.d
    networks:
      - frontend
      - backend

  dockergen:
    build:
      context: ./images/dockergen
      dockerfile: "Dockerfile"
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./images/dockergen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    networks:
      - backend

### site1
  php-fpm:
    image: php:7.2-fpm-alpine
    volumes_from:
      - nginx
    networks:
      - backend
    environment:
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_HOST=php-fpm

  fa:
    image: php:7.2-fpm-alpine
    volumes_from:
      - nginx
    networks:
      - backend
    environment:
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_HOST=fa
  php:
    image: index.docker.io/hsl888/php:latest
    volumes_from:
      - nginx
    volumes:
      - ./images/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./images/php/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - backend
    restart: always
    environment:
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_HOST=fa


### Networks Setup ############################################
#
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
